# Generated by Django 4.1.3 on 2022-11-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_count',
            field=models.IntegerField(default=1),
        ),
    ]
