# Generated by Django 4.1.3 on 2022-11-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_question_real_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
