# Generated by Django 4.1.3 on 2022-12-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_question_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='real_answer',
        ),
    ]
