# Generated by Django 4.2.2 on 2023-06-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0012_remove_question_real_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="audio_src_url",
        ),
    ]
